### ISSUE TITLE
Tasks break when run from IntelliJ Run tab

### ISSUE THREAD

**Issue by tpizza** [Freyskeyd/gulp-prompt#32]
When trying to run a task from the Gulp window within WebStorm or IntelliJ, Prompt throws a Syntax Error.

Here is the stack trace for the bug:
```

SyntaxError: Invalid regular expression: /.{1,0}/: numbers out of order in {} quantifier.
    at new RegExp (native)
    at breakLines (.\node_modules\gulp-prompt\node_modules\inquirer\lib\utils\screen-manager.js:108:15)
    at ScreenManager.render (.\node_modules\gulp-prompt\node_modules\inquirer\lib\utils\screen-manager.js:55:22)
    at Prompt.render (.\node_modules\gulp-prompt\node_modules\inquirer\lib\prompts\input.js:75:15)
    at Prompt._run (.\node_modules\gulp-prompt\node_modules\inquirer\lib\prompts\input.js:49:8)
    at Prompt.run (.\node_modules\gulp-prompt\node_modules\inquirer\lib\prompts\base.js:57:8)
    at Object.<anonymous> (.\node_modules\gulp-prompt\node_modules\inquirer\lib\ui\prompt.js:84:12)
    at module.exports (.\node_modules\gulp-prompt\node_modules\inquirer\node_modules\run-async\index.js:15:21)
    at AnonymousObservable.__subscribe (.\node_modules\gulp-prompt\node_modules\inquirer\lib\utils\utils.js:16:7)
    at AnonymousObservable.tryCatcher (.\node_modules\gulp-prompt\node_modules\inquirer\node_modules\rx-lite\rx.lite.js:63:31)
```

**Comment by mrkam** [comment]
Caused by old version of enquirer. See https://github.com/SBoudrias/Inquirer.js/issues/290

**Comment by shannonlal** [comment]
The latest version of gulp prompt is using the latest version of inquirer.js is this still an issues?

**Comment by shannonlal** [comment]
I am going to close this off since I haven't heard any issues for a year and it looks like the new version of inquirer will fix this
