### ISSUE TITLE
Ask once for multiple files in stream

### ISSUE THREAD

**Issue by ikari-pl** [Freyskeyd/gulp-prompt#9]
Currently if I have two files in the process, and pipe that to `prompt.confirm`, the question is asked twice, and, even worse, the process crashes no matter what you choose:

```js
gulp.src(paths.versionToBump) // get all the files to bump version in
    .pipe(prompt.confirm('Have you commited all the changes to be included by this version?'));
```

results in
```console
[?] Have you commited all the changes to be included by this version? No

C:\work\code\sndapi-js\node_modules\gulp-prompt\node_modules\inquirer\lib\inquirer.js:71
    this.rl.removeListener( "SIGINT", this.onForceClose );
            ^
TypeError: Cannot call method 'removeListener' of null
    at Object.<anonymous> (C:\work\code\sndapi-js\node_modules\gulp-prompt\node_modules\inquirer\lib\inquirer.js:71:13)
    at C:\work\code\sndapi-js\node_modules\gulp-prompt\node_modules\inquirer\node_modules\async\lib\async.js:232:13
    at C:\work\code\sndapi-js\node_modules\gulp-prompt\node_modules\inquirer\node_modules\async\lib\async.js:142:25
    at C:\work\code\sndapi-js\node_modules\gulp-prompt\node_modules\inquirer\node_modules\async\lib\async.js:229:17
    at Object.<anonymous> (C:\work\code\sndapi-js\node_modules\gulp-prompt\node_modules\inquirer\lib\inquirer.js:89:7)
    at Object.utils.runAsync (C:\work\code\sndapi-js\node_modules\gulp-prompt\node_modules\inquirer\lib\utils\utils.js:44:5)
    at Prompt.filter (C:\work\code\sndapi-js\node_modules\gulp-prompt\node_modules\inquirer\lib\prompts\base.js:198:9)
    at Prompt.done (C:\work\code\sndapi-js\node_modules\gulp-prompt\node_modules\inquirer\lib\prompts\base.js:68:10)
    at Prompt.<anonymous> (C:\work\code\sndapi-js\node_modules\gulp-prompt\node_modules\inquirer\lib\prompts\confirm.js:97:10)
    at Object.utils.runAsync (C:\work\code\sndapi-js\node_modules\gulp-prompt\node_modules\inquirer\lib\utils\utils.js:44:5)
```

and the question(s) is(are) in the form:
```console
[?] Have you commited all the changes to be included by this version? (y/N) [?] Are you sure? (y/N)
```

**Comment by pmhpereira** [comment]
Just tried the fix of syrenio and it works. Thanks!

Minor issue though: I did `npm install gulp-prompt`, but I didn't get the version with this merge. 

Don't you need to `npm publish` the updated code, with a bumped PATCH version (0.1.2 in this case)?

**Comment by Freyskeyd** [comment]
it's done

**Comment by pmhpereira** [comment]
Awesome! You rock! :smile:

**Comment by syrenio** [comment]
Yeah nice! :-)
